# Generated by Django 6.0 on 2026-01-07 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("long_description", models.TextField(blank=True, null=True)),
                ("price", models.PositiveIntegerField()),
                ("stock", models.PositiveIntegerField()),
                ("weight", models.FloatField(help_text="Weight in KG")),
                ("featured", models.BooleanField(default=False)),
                ("is_customizable", models.BooleanField(default=False)),
                ("images", models.JSONField(default=list)),
                ("available_colors", models.JSONField(default=list)),
                ("features", models.JSONField(default=list)),
                ("materials", models.JSONField(default=list)),
                ("care_instructions", models.JSONField(default=list)),
                ("dimensions", models.JSONField(blank=True, null=True)),
                ("related_products", models.JSONField(blank=True, null=True)),
                ("is_food_safe", models.BooleanField(default=True)),
                ("is_microwave_safe", models.BooleanField(default=False)),
                ("is_dishwasher_safe", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.category",
                    ),
                ),
            ],
        ),
    ]
