# Generated by Django 6.0 on 2026-01-08 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("cups_mugs", "Cups & Mugs"),
                            ("bowls", "Bowls"),
                            ("plates", "Plates"),
                            ("vases", "Vases"),
                            ("decorative", "Decorative pieces"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("dimensions", models.CharField(blank=True, max_length=100)),
                ("preferred_colors", models.CharField(blank=True, max_length=100)),
                ("timeline", models.CharField(blank=True, max_length=100)),
                ("budget_range", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomOrderImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="custom_orders/")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.customorder",
                    ),
                ),
            ],
        ),
    ]
