# Generated by Django 6.0 on 2026-01-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_customorder_customorderimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="customorder",
            name="admin_notes",
            field=models.TextField(
                blank=True, help_text="Internal notes for admin only"
            ),
        ),
        migrations.AddField(
            model_name="customorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("reviewed", "Reviewed"),
                    ("quoted", "Quoted"),
                    ("approved", "Approved"),
                    ("in_production", "In Production"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customorder",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
