"""
Django settings for basho_backend project.
Generated by 'django-admin startproject' using Django 6.0.
For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os

from pathlib import Path
from dotenv import load_dotenv


#aish impoorts:
from datetime import timedelta

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# load_dotenv(BASE_DIR/".env")

ENV_PATH = BASE_DIR / ".env"
load_dotenv(ENV_PATH)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-^u76pivvsyckfi6cph^ez5ufq7#&$3#xuygjc7h0m62^bwr=$o"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [

    "django.contrib.messages",

    'cloudinary_storage',
    "django.contrib.staticfiles",
    'cloudinary',
    
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    
    "rest_framework",
    'corsheaders',

    'apps.experiences',
    'apps.products',
    'apps.orders',
    'apps.accounts',
    "apps.corporate",
    "apps.reviews",
    "apps.main.apps.MainConfig",
    "rest_framework.authtoken",
]

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
}

JAZZMIN_SETTINGS = {
    # Admin titles
    "site_title": "Basho Admin",
    "site_header": "basho",
    "site_brand": "basho",
    "welcome_sign": "Welcome to Basho Admin Panel",

    # Logo (THIS is the key)
     "site_logo": None,
    "site_logo_classes": None,


    # Sidebar
    "show_sidebar": True,
    "navigation_expanded": True,

    # Theme (keep default look – good choice)
    "theme": "flatly",

    # ✅ CORRECT ICON MAPPING (IMPORTANT)
    "icons": {
        # Accounts
        "accounts.user": "fas fa-user",
        "accounts.emailotp": "fas fa-envelope",

        # Authentication
        "auth.group": "fas fa-users-cog",
        "authtoken.token": "fas fa-key",

        # Experiences
        "experiences.booking": "fas fa-calendar-check",
        "experiences.experience": "fas fa-mug-hot",
        "experiences.experienceslot": "fas fa-clock",
        "experiences.workshop": "fas fa-paint-brush",
        "experiences.workshopslot": "fas fa-hourglass",
        "experiences.workshopregistration": "fas fa-users",
        "experiences.StudioBooking": "fas fa-building",
        "experiences.UpcomingEvent": "fas fa-calendar-alt",

         
        # Orders & Payments
        "orders.Cart": "fas fa-shopping-cart",
        "orders.order": "fas fa-shopping-cart",
        "orders.payment": "fas fa-credit-card",
        "orders.transaction": "fas fa-receipt",
        "orders.paymentorder": "fas fa-file-invoice",

        # Products
        "products.product": "fas fa-box",
        "products.category": "fas fa-tags",
        "products.customorder": "fas fa-hammer",
        "products.customorderimage": "fas fa-image",

        # Corporate
        "corporate.corporateinquiry": "fas fa-building",

        # Reviews
         "reviews.Review": "fas fa-star",

         # Auth Token icon
         "authtoken.TokenProxy": "fas fa-key",
    },

    # Fallback icons
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-file",

    # Custom CSS (✔ path is correct)
    "custom_css": "admin/css/basho_admin.css",
}
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "basho_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "basho_backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
    }
}





# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"
USE_I18N = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"
 
#aishwarya changes: 
AUTH_USER_MODEL = "accounts.User"

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")

CORS_ALLOW_ALL_ORIGINS = True

GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
}




# Upload limits (10 MB per file)
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

TIME_ZONE = 'Asia/Kolkata'
USE_TZ = True
 
DEFAULT_FROM_EMAIL = "Basho by Shivangi <bashobyshivangi123@gmail.com>"

 
FRONTEND_URL = "http://localhost:3000"

RAZORPAY_KEY_ID = os.getenv("RAZORPAY_KEY_ID")
RAZORPAY_KEY_SECRET = os.getenv("RAZORPAY_KEY_SECRET")

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://basho-by-shivangi-tau.vercel.app",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS",
]
 
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = False  # True only in HTTPS
 
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Allows the app to be viewed inside the Hugging Face "App" tab
X_FRAME_OPTIONS = 'ALLOWALL'

# Fixes the "CSRF verification failed" login error
CSRF_TRUSTED_ORIGINS = [
    'https://suprajakshaya-kdon-v2.hf.space',
]