# Generated by Django 6.0 on 2026-01-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_booking_payment_amount_booking_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('visit_date', models.DateField()),
                ('time_slot', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('badge', models.CharField(default='✨ Upcoming', max_length=50)),
            ],
        ),
    ]
