# Generated by Django 6.0 on 2026-01-08 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0003_studiobooking_upcomingevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('group', 'Group'), ('private', 'Private'), ('experience', 'Experience')], max_length=20)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('experience_type', models.CharField(blank=True, choices=[('couples_date', 'Couple’s Date'), ('birthday_party', 'Birthday Party'), ('corporate', 'Corporate'), ('masterclass', 'Masterclass')], max_length=30, null=True)),
                ('description', models.TextField()),
                ('long_description', models.TextField()),
                ('images', models.JSONField(default=list)),
                ('duration', models.CharField(max_length=50)),
                ('min_participants', models.PositiveIntegerField()),
                ('max_participants', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('price_per_person', models.BooleanField(default=True)),
                ('includes', models.JSONField(default=list)),
                ('requirements', models.JSONField(blank=True, null=True)),
                ('provided_materials', models.JSONField(default=list)),
                ('location', models.CharField(max_length=200)),
                ('instructor', models.CharField(max_length=100)),
                ('take_home', models.CharField(max_length=200)),
                ('certificate', models.BooleanField(default=False)),
                ('lunch_included', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('available_spots', models.PositiveIntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='experiences.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('number_of_participants', models.PositiveIntegerField()),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='experiences.workshop')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='experiences.workshopslot')),
            ],
        ),
    ]
