# Generated by Django 6.0 on 2026-01-10 10:20

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0004_workshop_workshopslot_workshopregistration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name_plural': 'Experiences'},
        ),
        migrations.AlterModelOptions(
            name='studiobooking',
            options={'ordering': ['visit_date', 'time_slot'], 'verbose_name_plural': 'Studio Bookings'},
        ),
        migrations.AlterModelOptions(
            name='upcomingevent',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='workshop',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='workshopregistration',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='workshopslot',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.AddField(
            model_name='workshop',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='workshop',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='workshopregistration',
            name='payment_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workshopregistration',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='workshopregistration',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='workshopslot',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='workshopslot',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='certificate',
            field=models.BooleanField(default=False, help_text='Is certificate provided?'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='description',
            field=models.TextField(help_text='Short description for cards'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='duration',
            field=models.CharField(help_text="e.g., '3 hours', '2-3 hours'", max_length=50),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='experience_type',
            field=models.CharField(blank=True, choices=[('couples_date', "Couple's Date"), ('birthday_party', 'Birthday Party'), ('corporate', 'Corporate'), ('masterclass', 'Masterclass')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='featured',
            field=models.BooleanField(default=False, help_text='Show as featured workshop?'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='images',
            field=models.JSONField(default=list, help_text='List of image URLs/paths'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='includes',
            field=models.JSONField(default=list, help_text="List of what's included (materials, tools, etc.)"),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='instructor',
            field=models.CharField(default='Shivangi', max_length=100),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is workshop available for booking?'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='location',
            field=models.CharField(default='Basho Studio', max_length=200),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='long_description',
            field=models.TextField(help_text='Detailed description for workshop page'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='lunch_included',
            field=models.BooleanField(default=False, help_text='Is lunch included?'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='max_participants',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='min_participants',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='price',
            field=models.PositiveIntegerField(help_text='Price in rupees'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='price_per_person',
            field=models.BooleanField(default=True, help_text='If True, price is per person. If False, price is for the group.'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='provided_materials',
            field=models.JSONField(default=list, help_text='Materials provided by studio'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='requirements',
            field=models.JSONField(blank=True, help_text='What participants need to bring/know', null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='take_home',
            field=models.CharField(help_text='What participants can take home', max_length=200),
        ),
        migrations.AlterField(
            model_name='workshopregistration',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workshopregistration',
            name='number_of_participants',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='workshopslot',
            name='available_spots',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='workshopslot',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Is this slot open for bookings?'),
        ),
        migrations.AlterUniqueTogether(
            name='workshopslot',
            unique_together={('workshop', 'date', 'start_time')},
        ),
        migrations.AddIndex(
            model_name='workshopregistration',
            index=models.Index(fields=['email'], name='experiences_email_b6e066_idx'),
        ),
        migrations.AddIndex(
            model_name='workshopregistration',
            index=models.Index(fields=['created_at'], name='experiences_created_ce420a_idx'),
        ),
    ]
